version: '2'
services:
  db:
    image: centos/postgresql-94-centos7:latest
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USER: airbnb
      POSTGRESQL_PASSWORD: airbnb
      POSTGRESQL_DATABASE: airbnb
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
